name: Keeper Secrets Manager Github Action
on:
 workflow_dispatch:

jobs: 
 ksm-test-random:
  runs-on: ubuntu-latest

  steps:
   - name: Retreive Secrets From KSM
     id: ksecrets
     uses: Keeper-Security/ksm-action@master
     with:
       keeper-secret-config: ${{ secrets.KSM_CONFIG }}
       secrets: |
        IZhsUYqNgUZ7IwVZxRClnA/field/password > pwd
        IZhsUYqNgUZ7IwVZxRClnA/field/password > env:pwd
        IZhsUYqNgUZ7IwVZxRClnA/field/login > lng
        IZhsUYqNgUZ7IwVZxRClnA/field/login > env:lng

   - name: View login
     run: |
      echo "password: ${{ env.pwd }}"
      echo "login: ${{ env.lng }}"
